/* The icons this codebase uses, imported by name so the bundler ships only
   these. The previous wrapper imported Lucide's whole `icons` map — 1,749
   glyphs, roughly half a megabyte of client JavaScript — to render about
   eighty. A name outside this set renders the empty box the wrapper always
   drew, and the `icons` gate in check:ds fails on any literal name the set
   does not carry. Regenerate when you add an icon: the gate names it. */
import {
  Activity,
  Anchor,
  ArrowLeft,
  ArrowUpDown,
  ArrowUpRight,
  Award,
  BookOpen,
  Calculator,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CloudLightning,
  Club,
  Code,
  Compass,
  Download,
  Droplets,
  FilePenLine,
  Flag,
  Hash,
  Hourglass,
  Inbox,
  Key,
  LifeBuoy,
  LogOut,
  Mail,
  Map,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Minus,
  Monitor,
  Moon,
  Navigation,
  Package,
  Radar,
  Radio,
  Receipt,
  Route,
  Sailboat,
  Save,
  Search,
  Sheet,
  ShieldCheck,
  ShoppingBasket,
  Signature,
  SlidersHorizontal,
  Sun,
  Table,
  Ticket,
  TriangleAlert,
  Users,
  Vote,
  WifiOff,
  Wind,
  X,
} from "lucide-react";

export const ICONS = {
  Activity,
  Anchor,
  ArrowLeft,
  ArrowUpDown,
  ArrowUpRight,
  Award,
  BookOpen,
  Calculator,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CloudLightning,
  Club,
  Code,
  Compass,
  Download,
  Droplets,
  FilePenLine,
  Flag,
  Hash,
  Hourglass,
  Inbox,
  Key,
  LifeBuoy,
  LogOut,
  Mail,
  Map,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Minus,
  Monitor,
  Moon,
  Navigation,
  Package,
  Radar,
  Radio,
  Receipt,
  Route,
  Sailboat,
  Save,
  Search,
  Sheet,
  ShieldCheck,
  ShoppingBasket,
  Signature,
  SlidersHorizontal,
  Sun,
  Table,
  Ticket,
  TriangleAlert,
  Users,
  Vote,
  WifiOff,
  Wind,
  X,
} as const;

export type IconName = keyof typeof ICONS;
