-- Harbors, in launch order
insert into public.harbors (slug, name, status, coordinates, launch_year, position) values
  ('miami', 'Miami', 'open', E'25.7617° N — 80.1918° W', 2026, 1),
  ('los-angeles', 'Los Angeles', 'open', E'33.9803° N — 118.4517° W', 2026, 2),
  ('chicago', 'Chicago', 'waitlist', E'41.8781° N — 87.6298° W', 2027, 3),
  ('new-york', 'New York', 'waitlist', E'40.7128° N — 74.0060° W', 2027, 4);

-- Voyages & salons (dates relative to launch summer 2026)
insert into public.voyages (slug, title, class, kind, harbor_id, starts_at, ends_at, coordinates, distance_nm, berths_total, price_cents, status, blurb, description, media, min_tier) values
  ('the-long-way-home', 'The long way home.', 'sea', 'voyage',
    (select id from public.harbors where slug='los-angeles'),
    '2026-07-26T06:00:00-07:00', '2026-07-26T20:00:00-07:00',
    E'33.9803° N — 118.4517° W', 26, 24, 18500, 'scheduled',
    'A Sea Day out of Marina del Rey. Twenty-six nautical miles, no agenda past the swell.',
    'Boards at first light. Coffee on the dock, lines off at 06:00 sharp. The route runs south past the breakwater, holds at Point Vicente for a long lunch on the water, and takes the golden hour back in. Bring a layer; the wind writes the schedule.',
    'dawn', 'regional'),
  ('salon-no-9', 'Salon No. IX.', 'sky', 'salon',
    (select id from public.harbors where slug='los-angeles'),
    '2026-08-01T19:00:00-07:00', '2026-08-02T01:00:00-07:00',
    E'33.9850° N — 118.4695° W', null, 60, 9500, 'scheduled',
    'An Overnight ashore. Long tables, low light, one unrepeatable room.',
    'Doors at 19:00. Dinner is served family-style at three long tables; the conversation is the program. After midnight the room turns over to records and the terrace. Dress like you mean it.',
    'dusk', 'regional'),
  ('biscayne-crossing', 'The Biscayne crossing.', 'sea', 'voyage',
    (select id from public.harbors where slug='miami'),
    '2026-08-08T07:00:00-04:00', '2026-08-08T19:00:00-04:00',
    E'25.7617° N — 80.1918° W', 31, 24, 21000, 'scheduled',
    'Miami''s flagship Sea Day. Thirty-one nautical miles across the bay and back.',
    'Out through Government Cut with the sunrise, south along the reef line, anchor and swim at Sands Key. The manifest closes 72 hours out. Weather holds are called by 18:00 the night before.',
    'day', 'regional'),
  ('port-day-tulum-tables', 'Long tables, Key Biscayne.', 'shore', 'salon',
    (select id from public.harbors where slug='miami'),
    '2026-08-15T11:00:00-04:00', '2026-08-15T17:00:00-04:00',
    E'25.6907° N — 80.1620° W', null, 40, 7500, 'scheduled',
    'A Port Day on the sand. Salt, citrus, and an afternoon that refuses to end.',
    'A beach takeover in the Cape Florida shade: long tables, cold seafood, colder wine. Wellness block at 11:00 for the committed; everyone else arrives at noon like adults.',
    'day', 'regional'),
  ('night-passage-catalina', 'Night passage: Catalina.', 'sky', 'voyage',
    (select id from public.harbors where slug='los-angeles'),
    '2026-08-22T21:00:00-07:00', '2026-08-23T09:00:00-07:00',
    E'33.3428° N — 118.3282° W', 29, 16, 32000, 'scheduled',
    'An Overnight at sea. Twenty-nine nautical miles by starlight to Two Harbors.',
    'Lines off at 21:00. The city drops away in twenty minutes; the Milky Way takes the watch. Bunks below for those who want them, the cockpit for those who don''t. Breakfast on the isthmus.',
    'dusk', 'national'),
  ('regatta-day-one', 'Season II regatta, day one.', 'sea', 'voyage',
    (select id from public.harbors where slug='miami'),
    '2026-09-05T09:00:00-04:00', '2026-09-05T18:00:00-04:00',
    E'25.7907° N — 80.1300° W', 18, 32, 14500, 'scheduled',
    'Crews are drawn by lot. Nobody has sailed before. That''s the point.',
    'Four boats, four crews, one course inside the bay. Skippers teach as you go; the trophy is small and the bragging rights are not. Fathoms double for crew who return for day two.',
    'day', 'regional'),
  ('the-wardroom-sessions', 'The Wardroom sessions.', 'sky', 'salon',
    (select id from public.harbors where slug='los-angeles'),
    '2026-07-24T20:00:00-07:00', '2026-07-25T00:00:00-07:00',
    E'33.9803° N — 118.4517° W', null, 48, 0, 'live',
    'Tonight. Members and one guest. The listening bar takes the wheel.',
    'A hi-fi salon in the boathouse: two turntables, one rule — nobody talks over the record. Walk-ups take the waitlist at the gangway.',
    'dusk', 'regional'),
  ('gulf-stream-run', 'The Gulf Stream run.', 'sea', 'voyage',
    (select id from public.harbors where slug='miami'),
    '2026-09-19T06:30:00-04:00', '2026-09-19T21:00:00-04:00',
    E'26.0000° N — 79.5000° W', 42, 20, 26500, 'weather_hold',
    'Forty-two nautical miles into blue water. Currently under weather hold.',
    'The stream decides, we obey. If the window opens we run east at dawn and ride the current north. Weather hold means your berth is safe and your card is not charged until we call it.',
    'day', 'national'),
  ('chicago-founding-salon', 'Chicago: the founding salon.', 'sky', 'salon',
    (select id from public.harbors where slug='chicago'),
    '2027-05-15T19:00:00-05:00', '2027-05-16T00:00:00-05:00',
    E'41.8781° N — 87.6298° W', null, 80, 0, 'scheduled',
    'The third harbor opens. Founding berths go to the waitlist first.',
    'One night to set the tone for a city. The founding class is drawn from the waitlist in order; berths that go unclaimed after 72 hours pass down the roll.',
    'dusk', 'regional');

-- The Dispatch
insert into public.dispatch_posts (slug, title, dek, body, tag, published_at) values
  ('berths-are-few-by-design', 'Berths are few by design.',
   'On scarcity as a courtesy, not a tactic.',
   E'Every boat we charter could be bigger. Every salon could take another forty names. We keep the manifests short because the point is the people, and people don''t happen in a crowd.\n\nA Sea Day with twenty-four aboard has a shape: you meet everyone by the second tack, and by the swim stop nobody is checking the time. Double it and you get a party — pleasant, forgettable, available anywhere.\n\nSo when the berths run out, they''re out. The waitlist is honest and the release order is the order you joined it. That''s the whole system. It isn''t a velvet rope; it''s a small boat.',
   'Clubhouse', '2026-07-06T09:00:00-07:00'),
  ('what-the-wind-writes', 'What the wind writes.',
   'Weather holds, explained once and for all.',
   E'Three times this season we''ve called a weather hold, and three times the same questions arrive. Here is the manifest on the matter.\n\nA hold is not a cancellation. Your berth stays yours; your card is not charged until we sail. We call holds by 18:00 the night before — earlier when the models agree, which they rarely do.\n\nWe hold for wind over 25 knots sustained, lightning inside twenty nautical miles, or seas that would turn lunch into a rodeo. We do not hold for rain. Rain is weather; the rest is risk.',
   'Seamanship', '2026-06-22T08:00:00-07:00'),
  ('the-fathom-standard', 'The fathom standard.',
   'Miles, not likes: how the ledger works.',
   E'A fathom is six feet of depth. In the club it''s the unit of showing up.\n\nYou earn fathoms by boarding — voyages pay by the nautical mile, salons by the night. You earn them by crewing the regatta, by bringing the guest who becomes a member, by writing the Dispatch piece everyone forwards.\n\nYou do not earn them by posting. The Wardroom is a room, not a stage; hails are a nod across it, not a scoreboard. The ledger rewards water under the keel, and the rewards — first call on scarce berths, the annual crossing draw — are things money is deliberately bad at buying.',
   'Clubhouse', '2026-06-01T10:00:00-07:00'),
  ('season-two-manifest', 'The Season II manifest.',
   'Two harbors, nineteen sailings, one crossing.',
   E'Season II runs July through October: nineteen sailings out of Marina del Rey and Government Cut, six salons ashore, and one crossing we''ll announce when the paperwork clears.\n\nMiami leads the calendar this year — the Biscayne crossing, the reef line runs, the regatta. Los Angeles answers with the night passages and the listening bar.\n\nChicago and New York: 2027. The waitlists are open and the founding berths come off them in order. The manifest lands each Sunday. Read it before the berths go; they go fast now.',
   'Manifest', '2026-07-20T09:00:00-07:00');

-- Seeded Wardroom posts (author_name only; live posts join profiles)
insert into public.wardroom_posts (author_name, body, voyage_id, created_at) values
  ('Mara V.', 'Twenty-six miles and my shoulders still know it. Whoever called the swim stop at Point Vicente: the club owes you a drink.', (select id from public.voyages where slug='the-long-way-home'), '2026-07-20T18:24:00-07:00'),
  ('Deshawn K.', 'Salon IX table three, if the conversation about lighthouses is continuing somewhere, I want in.', (select id from public.voyages where slug='salon-no-9'), '2026-07-21T09:12:00-07:00'),
  ('Ines R.', 'Crewing the regatta again. Zero sailing experience, one trophy, no notes. Sign up before you think about it.', (select id from public.voyages where slug='regatta-day-one'), '2026-07-22T14:47:00-07:00');
